version: '3.9'

volumes:
  pg_data:

networks:
  backend:

services:
  async:
    build: .
    networks:
      - backend
    depends_on:
      postgredb:
        condition: service_healthy

  postgredb:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d netology_asyncio" ]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
      - ./logs:/var/log

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - '9000:8978'
    depends_on:
      - postgredb
    networks:
      - backend
